data_light <- read.csv("./exdata%2Fdata%2Fhousehold_power_consumption/household_power_consumption.txt", header = TRUE, sep =";")
date1 <- as.Date("01/02/2007", "%d/%m/%Y")
date2 <- as.Date("02/02/2007", "%d/%m/%Y")
data_light$Date <- as.Date(data_light$Date, "%d/%m/%Y")
data_resume <- data_light[data_light$Date >= date1 & data_light$Date <= date2, ]
data_resume$Time <- strptime(data_resume$Time, "%H:%M:%S")
data_resume$Sub_metering_1 <- as.numeric(as.character(data_resume$Sub_metering_1))
data_resume$Sub_metering_2 <- as.numeric(as.character(data_resume$Sub_metering_2))
data_resume$Sub_metering_3 <- as.numeric(as.character(data_resume$Sub_metering_3))
plot(data_resume$Time, data_resume$Sub_metering_1, type = "l", xlab="", ylab="Energy sub metering")
lines(data_resume$Time, data_resume$Sub_metering_2, col="Red")
lines(data_resume$Time, data_resume$Sub_metering_3, col= "Blue")
legend("topright", lwd = 2, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.75)
dev.copy(png, file ="plot3.png")
dev.off()